services:
  app:
    build: .
    container_name: app-container
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=webservice_development
    volumes:
      - .:/myapp
    networks:
      - webservice-network

  db:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webservice_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - webservice-network

volumes:
  postgres-data:

networks:
  webservice-network:
    driver: bridge
