version: '3'
services:
  db:
    image: postgres:16 # PostgreSQL 16 のイメージ
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # パスワードの設定（後で変更できます）
      POSTGRES_DB: webservice_development # データベース名
    ports:
      - "5432:5432"  # PostgreSQL のポートをマッピング
    volumes:
      - postgres-data:/var/lib/postgresql/data # データ永続化のためのボリューム
    networks:
      - webservice-network

volumes:
  postgres-data:

networks:
  webservice-network:
    driver: bridge
