default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  username: myapp
  password: password
  database: myapp_development


test:
  <<: *default
  host: localhost
  username: myapp
  password: password
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: myapp
  host: <%= ENV["DB_HOST"] %>
  password: <%= ENV["DB_PASSWORD"] %>

