name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: project-a
  ECS_CLUSTER: ProjectA-ecs-cluster
  ECS_SERVICE: ProjectA-ecs-service
  ECS_TASK_DEFINITION: .github/workflows/task-definition.json
  CONTAINER_NAME: ECScontainer

jobs:
  deploy:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 060795905234.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build, tag, and push image to Amazon ECR
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG 060795905234.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push 060795905234.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update ECS task definition
        run: |
          TASK_DEF=$(aws ecs describe-task-definition --task-definition ECS-task --query taskDefinition)
          echo $TASK_DEF | jq '.containerDefinitions[0].image="060795905234.dkr.ecr.ap-northeast-1.amazonaws.com/project-a:'$IMAGE_TAG'"' > $ECS_TASK_DEFINITION
          echo "Updated task definition saved to $ECS_TASK_DEFINITION"

      - name: Register new ECS task definition
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://$ECS_TASK_DEFINITION --query taskDefinition.taskDefinitionArn --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition $TASK_DEF_ARN
